# Generated by Django 4.1.2 on 2022-10-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=10)),
                ("date_of_foundation", models.DateField()),
                ("address", models.CharField(max_length=256)),
                ("number_of_employees", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("full_description", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[("FCM", "fuel cell module"), ("BAT", "battery pack")],
                        max_length=3,
                    ),
                ),
                ("model_name", models.CharField(max_length=32)),
                (
                    "indicative_pricing",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "pricing_currency",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("USD", "USD"), ("PLN", "PLN")],
                        max_length=3,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("job_title", models.CharField(max_length=32)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=64)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.company",
                    ),
                ),
            ],
        ),
    ]
