# Generated by Django 4.1.2 on 2022-11-01 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Battery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Company's name for the product.", max_length=32
                    ),
                ),
                (
                    "total_energy",
                    models.PositiveIntegerField(verbose_name="Total energy [kWh]"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full company name.", max_length=100),
                ),
                (
                    "short_name",
                    models.CharField(
                        help_text="Shortened name of the company.", max_length=10
                    ),
                ),
                (
                    "year_of_foundation",
                    models.PositiveIntegerField(
                        help_text="Year of the company's foundation."
                    ),
                ),
                ("address", models.TextField(help_text="Full address of the company.")),
                (
                    "number_of_employees",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Approximate number of employees.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Short description of the company."),
                ),
                ("last_modified", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FuelCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Company's name for the product.", max_length=32
                    ),
                ),
                (
                    "rated_power",
                    models.PositiveIntegerField(verbose_name="Rated power [kW]"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Company owning the product.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short summary of the entry.", max_length=128
                    ),
                ),
                (
                    "full_description",
                    models.TextField(help_text="Full description of the event."),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, help_text="Date of the entry."),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_title",
                    models.CharField(
                        help_text="Short summary of a general goal of a company.",
                        max_length=64,
                    ),
                ),
                ("additional_info", models.TextField()),
                (
                    "start_year",
                    models.PositiveIntegerField(
                        help_text="The year, that the work on this goal is planned to start."
                    ),
                ),
                (
                    "end_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The year, that the work on this goal is planned to end.",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FuelCellPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date that the offer was made.")),
                (
                    "expiration_date",
                    models.DateField(help_text="Date that the offer will expire."),
                ),
                (
                    "indicative_pricing",
                    models.DecimalField(
                        decimal_places=2, help_text="indicative_pricing.", max_digits=16
                    ),
                ),
                (
                    "pricing_currency",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("USD", "USD"), ("PLN", "PLN")],
                        help_text="Currency of the pricing.",
                        max_length=3,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.fuelcell",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "job_title",
                    models.CharField(
                        help_text="Function in the company.", max_length=32
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=64)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BatteryPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date that the offer was made.")),
                (
                    "expiration_date",
                    models.DateField(help_text="Date that the offer will expire."),
                ),
                (
                    "indicative_pricing",
                    models.DecimalField(
                        decimal_places=2, help_text="indicative_pricing.", max_digits=16
                    ),
                ),
                (
                    "pricing_currency",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("USD", "USD"), ("PLN", "PLN")],
                        help_text="Currency of the pricing.",
                        max_length=3,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.battery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="battery",
            name="company",
            field=models.ForeignKey(
                help_text="Company owning the product.",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.company",
            ),
        ),
    ]
