# Generated by Django 4.1.2 on 2022-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_date_batterypricing_received_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="short_name",
            field=models.CharField(
                default="unknown",
                help_text="Shortened name of the company.",
                max_length=10,
            ),
        ),
    ]
