# Generated by Django 4.1.2 on 2022-11-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_indicative_pricing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="date_of_foundation",
        ),
        migrations.AddField(
            model_name="company",
            name="year_of_foundation",
            field=models.PositiveIntegerField(
                default=None, help_text="Year of the company's foundation."
            ),
            preserve_default=False,
        ),
    ]
