# Generated by Django 4.1.2 on 2022-11-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_company_date_of_foundation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(help_text="Full address of the company."),
        ),
    ]
