# Generated by Django 4.1.2 on 2022-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_company_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="short_name",
            field=models.CharField(
                help_text="Shortened name of the company.", max_length=10
            ),
        ),
    ]
