# Generated by Django 4.1.2 on 2022-11-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_company_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description of the company."
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="year_of_foundation",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year of the company's foundation.", null=True
            ),
        ),
    ]
