# Generated by Django 4.1.2 on 2022-11-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("catalog", "0004_alter_company_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="battery",
            name="product",
        ),
        migrations.RemoveField(
            model_name="fuelcell",
            name="product",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="product",
        ),
        migrations.AddField(
            model_name="battery",
            name="company",
            field=models.ForeignKey(
                default=None,
                help_text="Company owning the product.",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="battery",
            name="model_name",
            field=models.CharField(
                default=None, help_text="Company's name for the product.", max_length=32
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fuelcell",
            name="company",
            field=models.ForeignKey(
                default=None,
                help_text="Company owning the product.",
                on_delete=django.db.models.deletion.PROTECT,
                to="catalog.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fuelcell",
            name="model_name",
            field=models.CharField(
                default=None, help_text="Company's name for the product.", max_length=32
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricing",
            name="object_id",
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
