# Generated by Django 4.1.2 on 2022-11-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_company_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="job_title",
            new_name="function",
        ),
    ]
