# Generated by Django 4.1.2 on 2022-11-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_rename_job_title_employee_function"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="function",
            field=models.CharField(
                choices=[
                    ("SERV", "serviceman"),
                    ("ENGI", "engineer"),
                    ("SALE", "salesman"),
                    ("MANA", "management"),
                    ("RCPT", "reception"),
                    ("SECU", "security"),
                ],
                help_text="Function in the company.",
                max_length=4,
            ),
        ),
    ]
